name: Run Hello

on:
  push:
  workflow_dispatch:

jobs:
  run-hello1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt update && sudo apt install -y g++

      - name: Compile hello.cpp
        run: g++ hello.cpp -o hello

      - name: Run hello
        run: ./hello
